language: ruby
rvm:
  - 2.5.3

env:
  global:
    - RUBY_GC_MALLOC_LIMIT=90000000
    - RUBY_GC_HEAP_FREE_SLOTS=200000

services:
  - postgresql

before_script:
  - cp config/database.travis.yml config/database.yml
  - psql -c "CREATE USER \"wblog-api\" WITH PASSWORD 'wblog-api';" -U postgres
  - psql -c "DROP DATABASE IF EXISTS \"wbooks-api_test\";" -U postgres
  - psql -c "CREATE DATABASE \"wblog-api_test\" ENCODING 'utf8';" -U postgres
  - bundle exec rake db:migrate

before_install:
  - "echo '--colour' > ~/.rspec"
  - "echo 'gem: --no-document' > ~/.gemrc"
  # Solves rainbow issue: https://github.com/sickill/rainbow/issues/48
  - gem update --system

script:
  - bundle exec rspec spec -fd
  - bundle exec rubocop app spec -R --format simple

cache:
  bundler: true
